[package]
name = "bcache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.15.0"
clap = { version = "4.3.17", features = ["derive"] }
rand = "0.8.5"
serde_json = "1.0.104"
